name: MCEngineCurrency
version: ${version}
main: io.github.mcengine.spigotmc.currency.MCEngineCurrency
author: MCEngine
description: MCEngine Currency
api-version: 1.18
softdepend: [HeadDatabase]
commands:
  currency:
    description: Add, Check, Pay
    usage: /currency <add || check || pay>